### PR TITLE
Update README with VIPS library installation step

### PR DESCRIPTION
**Pull request by belgoros**
The setup section seems to miss this step.
When following the setup instructions, you can get an error message in case you have no VIPS library installed yet.

### CODE REVIEW

**Review by stevepolitodesign — COMMENTED** [review]
Thank you for opening this. Out of curiosity, did the setup script print this error for you?

https://github.com/thoughtbot/botcasts/blob/5fbef700a3ca9bbe055bb1e06899343404106376/bin/setup#L17-L22

Ideally, we could rely on the setup script to account for this.

**Comment by belgoros** [comment]
@stevepolitodesign Yep, exactly, this is what I got during the setup.

**Comment by stevepolitodesign** [comment]
Maybe instead of handling that specific case, we add a requirements heading under Setup section? 

```markdown
### Requirements

- Ruby `3.3.0`
- [libvips](https://www.libvips.org/install.html) 
```

**Comment by belgoros** [comment]
Sounds good to me as the requirements are totally missing here (what normally should precede any installation step). It's up you. I can bring the change whatever you choose 😉.

**Comment by stevepolitodesign** [comment]
Good call, let's place it before Setup.

**Pull request merged**
